###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/controller/refresh/impl/per_bank.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param


class PerBank(Component):
    impl = "PerBank"
    postponable = Param(bool, default=False)
    max_postponed = Param(int, default=8)
